#ifndef DEFINE_H
#define DEFINE_H

#define BMPSIG 0x4d42
#define BITMAPINFOHEADERSIZE 40
#define HEADERSIGOFFSET 0x0
#define FILESIZEOFFSET 0X2
#define DATAOFFSET 0xa
#define SIZEOFFSET 0xe
#define WIDTHOFFSET 0x12
#define HEIGHTOFFSET 0x16
#define PLANESOFFSET 0x1a
#define BITSPERPIXELOFFSET 0x1c
#define COMPRESSIONOFFSET 0x1e
#define IMAGESIZEOFFSET 0x22
#define XPIXELSPERMOFFSET 0x26
#define COLORUSEDOFFSET 0x2e
#define IMPORTANTCOLORSOFFSET 0X32
#define COLORTABLEOFFSET 0X36

#endif
